### ISSUE TITLE
Debug sitemap errors in log 

### ISSUE THREAD

**Issue by MikeHook** [MikeHook/MSTC#27]
1146459	0	4171	2/21/2015 11:25:41 AM	Error	Error adding to SiteMapProvider in loadNodes(): System.InvalidOperationException: Multiple nodes with the same URL '/' were found. XmlSiteMapProvider requires that sitemap nodes have unique URLs.
   at System.Web.StaticSiteMapProvider.AddNode(SiteMapNode node, SiteMapNode parentNode)
   at umbraco.presentation.nodeFactory.UmbracoSiteMapProvider.loadNodes(String parentId, SiteMapNode parentNode)
   
   1146489	0	1246	2/21/2015 12:16:39 PM	Error	Couldn't find any page with the nodeId = 1246. This is most likely caused by the page isn't published!
Parameter name: nodeId

**Comment by MikeHook** [comment]
Just disabled it. Simples.
